services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"    

    volumes: &common-volumes
      - .:/app
      - ~/.config/Aloncie:/home/rwal/.config/Aloncie
      - ~/.cache/Aloncie:/home/rwal/.cache/Aloncie
      - ${HOME}/.local/share/Aloncie/Rwal/downloads:/home/rwal/.local/share/Aloncie/Rwal/downloads      
      - ~/Pictures/Rwal:/home/rwal/Pictures/Rwal
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run/user/${UID:-1000}/bus:/run/user/${UID:-1000}/bus:ro
      - ./build:/app/build
    environment: &common-env
      - DISPLAY=${DISPLAY}
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${UID:-1000}/bus
      - HOST_HOME=${HOME}
    command: ./rwal

  rwal:
    image: aloncie/rwal:latest
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: /usr/local/bin/rwal
    volumes: *common-volumes
    environment: *common-env
    stdin_open: true
    tty: true
