services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: &common-volumes
      - .:/app
      - ~/.config/Aloncie:/home/developer/.config/Aloncie
      - ~/.cache/Aloncie:/home/developer/.cache/Aloncie
      - ~/Pictures/Rwal:/home/developer/Pictures/Rwal
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run/user/${UID:-1000}/bus:/run/user/${UID:-1000}/bus:ro
      - ./build:/app/build
    environment: &common-env
      - DISPLAY=${DISPLAY}
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${UID:-1000}/bus
      - HOME=/home/developer
    command: ./rwal

  rwal:
    image: aloncie/rwal:latest
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: /usr/local/bin/rwal
    volumes: *common-volumes
    environment: *common-env
    stdin_open: true
    tty: true


